### ISSUE TITLE
Blog post link overlaying the page

### ISSUE THREAD

**Issue by Berkmann18** [esparkman/gridsome-starter-netlify-netlifycms-tailwindcss#2]
Whenever I click on any links on the home page (whether it's "Home", "About" or two top posts), the URL used is one of the last posts which seems to come up even when being slightly out of the "clickable areas".
Inspecting each link leads to seeing the correct URLs being set for the afore-mentioned sections but clicking them doesn't work as expected.

/ref https://github.com/Berkmann18/gridsome-starter-netlify-netlifycms-tailwindcss.git

**Comment by esparkman** [comment]
This has been resolved with the following commit: https://github.com/esparkman/gridsome-starter-netlify-netlifycms-tailwindcss/commit/617d97975d4ef040c75262521f1f0279654ccf65
